#pragma once
#include <math.h>
#include <gkyl_util.h>

EXTERN_C_BEG

GKYL_CU_DH double gk_numerical_diffusion_order2_vol_1x1v_ser_p1_varnu_diffdirsx(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_1x1v_ser_p1_varnu_diffdirsx(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);

GKYL_CU_DH double gk_numerical_diffusion_order2_surfx_1x1v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order2_surfx_1x1v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_lower_zero_flux_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_lower_bound_local_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_lower_bound_local_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_lower_bound_recovery_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_upper_zero_flux_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_upper_bound_local_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_upper_bound_local_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_upper_bound_recovery_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_surfx_1x1v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order4_surfx_1x1v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_lower_zero_flux_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_lower_bound_local_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_lower_bound_local_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_lower_bound_recovery_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_upper_zero_flux_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_upper_bound_local_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_upper_bound_local_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_upper_bound_recovery_1x1v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);

GKYL_CU_DH double gk_numerical_diffusion_order2_vol_1x2v_ser_p1_varnu_diffdirsx(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_1x2v_ser_p1_varnu_diffdirsx(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);

GKYL_CU_DH double gk_numerical_diffusion_order2_surfx_1x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order2_surfx_1x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_lower_zero_flux_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_lower_bound_local_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_lower_bound_local_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_lower_bound_recovery_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_upper_zero_flux_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_upper_bound_local_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_upper_bound_local_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_upper_bound_recovery_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_surfx_1x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order4_surfx_1x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_lower_zero_flux_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_lower_bound_local_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_lower_bound_local_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_lower_bound_recovery_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_upper_zero_flux_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_upper_bound_local_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_upper_bound_local_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_upper_bound_recovery_1x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);

GKYL_CU_DH double gk_numerical_diffusion_order2_vol_2x2v_ser_p1_varnu_diffdirsx(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_vol_2x2v_ser_p1_varnu_diffdirsxz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_vol_2x2v_ser_p1_varnu_diffdirsz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_2x2v_ser_p1_varnu_diffdirsx(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_2x2v_ser_p1_varnu_diffdirsxz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_2x2v_ser_p1_varnu_diffdirsz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);

GKYL_CU_DH double gk_numerical_diffusion_order2_surfx_2x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order2_surfx_2x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_lower_zero_flux_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_lower_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_lower_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_lower_bound_recovery_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_upper_zero_flux_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_upper_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_upper_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_upper_bound_recovery_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_surfx_2x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order4_surfx_2x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_lower_zero_flux_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_lower_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_lower_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_lower_bound_recovery_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_upper_zero_flux_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_upper_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_upper_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_upper_bound_recovery_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);

GKYL_CU_DH double gk_numerical_diffusion_order2_surfz_2x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order2_surfz_2x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfz_lower_zero_flux_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfz_lower_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagz_lower_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagz_lower_bound_recovery_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfz_upper_zero_flux_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfz_upper_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagz_upper_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagz_upper_bound_recovery_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_surfz_2x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order4_surfz_2x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfz_lower_zero_flux_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfz_lower_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagz_lower_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagz_lower_bound_recovery_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfz_upper_zero_flux_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfz_upper_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagz_upper_bound_local_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagz_upper_bound_recovery_2x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);

GKYL_CU_DH double gk_numerical_diffusion_order2_vol_3x2v_ser_p1_varnu_diffdirsx(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_vol_3x2v_ser_p1_varnu_diffdirsxy(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_vol_3x2v_ser_p1_varnu_diffdirsxyz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_vol_3x2v_ser_p1_varnu_diffdirsxz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_vol_3x2v_ser_p1_varnu_diffdirsy(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_vol_3x2v_ser_p1_varnu_diffdirsyz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_vol_3x2v_ser_p1_varnu_diffdirsz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_3x2v_ser_p1_varnu_diffdirsx(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_3x2v_ser_p1_varnu_diffdirsxy(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_3x2v_ser_p1_varnu_diffdirsxyz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_3x2v_ser_p1_varnu_diffdirsxz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_3x2v_ser_p1_varnu_diffdirsy(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_3x2v_ser_p1_varnu_diffdirsyz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_vol_3x2v_ser_p1_varnu_diffdirsz(const double *w, const double *dx, const double *nu, const double *jacobgeo_inv, const double *Jfin, double* GKYL_RESTRICT out);

GKYL_CU_DH double gk_numerical_diffusion_order2_surfx_3x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order2_surfx_3x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_lower_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_lower_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_upper_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfx_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagx_upper_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_surfx_3x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order4_surfx_3x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_lower_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_lower_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_upper_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfx_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagx_upper_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);

GKYL_CU_DH double gk_numerical_diffusion_order2_surfy_3x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order2_surfy_3x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfy_lower_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfy_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagy_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagy_lower_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfy_upper_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfy_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagy_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagy_upper_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_surfy_3x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order4_surfy_3x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfy_lower_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfy_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagy_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagy_lower_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfy_upper_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfy_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagy_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagy_upper_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);

GKYL_CU_DH double gk_numerical_diffusion_order2_surfz_3x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order2_surfz_3x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfz_lower_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfz_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagz_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagz_lower_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfz_upper_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_surfz_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagz_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order2_boundary_diagz_upper_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_surfz_3x2v_ser_p1_varnu(GKYL_CU_DH double gk_numerical_diffusion_order4_surfz_3x2v_ser_p1_varnu(const double *wc, const double *dxc, const double *nul, const double *nuc, const double *nur, const double *jacobgeo_invl, const double *jacobgeo_invc, const double *jacobgeo_invr, const double *Jfl, const double *Jfc, const double *Jfr, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfz_lower_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfz_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagz_lower_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagz_lower_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfz_upper_zero_flux_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_surfz_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuEdge, const double *nuSkin, const double *jacobgeo_invEdge, const double *jacobgeo_invSkin, int edge, const double *JfEdge, const double *JfSkin, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagz_upper_bound_local_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);
GKYL_CU_DH double gk_numerical_diffusion_order4_boundary_diagz_upper_bound_recovery_3x2v_ser_p1_varnu(const double *wSkin, const double *dxSkin, const double *nuSkin, const double *nuGhost, const double *jacobgeo_invSkin, const double *jacobgeo_invGhost, int edge, const double *JfSkin, const double *JfGhost, double* GKYL_RESTRICT out);


EXTERN_C_END
