# Makefile for desc_grid standalone tool.
# Requires gkeyll to be built and installed (default: ~/gkylsoft).
# Usage:
#   make desc_grid
#   ./desc_grid <input_dir> <name>

include ${HOME}/gkylsoft/gkeyll/share/Makefile
