name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-openblas
      run: sudo apt-get install libopenblas-dev
    - name: where-openblas
      run: dpkg -L libopenblas-pthread-dev
    - name: install-lapacke
      run: sudo apt-get install liblapacke-dev
    - name: where-liblapacke-dev
      run: dpkg -L liblapacke-dev    
    - name: install-deps
      run: cd install-deps; ./mkdeps.sh --build-superlu=yes; cd ..
    - name: make
      run: make CC=clang -j LAPACK_INC=/usr/include/x86_64-linux-gnu/openblas-pthread LAPACK_LIB="/usr/lib/x86_64-linux-gnu/liblapacke.a /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas.a /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.a" -j
    - name: make check
      run: make CC=clang check -j LAPACK_INC=/usr/include/x86_64-linux-gnu/openblas-pthread LAPACK_LIB="/usr/lib/x86_64-linux-gnu/liblapacke.a"
