name: Mac Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-superlu
      run: cd install-deps; ./mkdeps.sh  --build-superlu=yes; cd ..    
    - name: make
      run: make -j
    - name: make check
      run: make check -j
